version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@b-vitamins"
    labels:
      - "dependencies"
      - "python"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@b-vitamins"
    labels:
      - "dependencies"
      - "github-actions"
